
spring:
  jpa:
    hibernate:
      ddl-auto: none

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ${REGION}
      auto: false
    stack:
      auto: false