server:
  port: 8080

spring:
  profiles:
    active: ${PROFILE_ACTIVE}
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  kafka:
    bootstrap-servers: "kafka-controller-headless.kafka.svc.cluster.local:9092"
    properties:
      security.protocol: PLAINTEXT # 프로토콜 명시
      bootstrap.servers.protocol.map: CLIENT:PLAINTEXT
      client.id: "team-kafka-client-${random.uuid}" # 클라이언트 ID 지정
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      transactional.id: "team-transaction"
#      enable.idempotence: true # true 시 중복 전송 방지, acks=all과 함께 사용, 3.0부터 true가 default
#      acks: "all" # all 이 default
    consumer:
      group-id: "team-service-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      isolation-level: read_committed
#      enable-auto-commit: true
    streams:
      application-id: "team-streams-app"
      processing.guarantee: exactly_once_v2  # default: at_least_once
#      properties:
#        commit.interval.ms: 100  # 트랜잭션 커밋 주기, exactly_once_v2 사용 시 권장 값 100ms (default가 100ms임)

feign:
  chatflow:
    member: ${MEMBER_SERVICE_URL}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
      auto: false
    stack:
      auto: false

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /teams/swagger
    display-request-duration: true
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /teams/v3/api-docs
    groups:
      enabled: true

tag:
  version: 1.0.0